### PR TITLE
Russian translation added

### PR DESCRIPTION
**Pull request by Sad-Scientist**

### CODE REVIEW

**Comment by LukeStonehm** [comment]
I'll pull this and see the effect before merging

**Comment by D-side** [comment]
I was curating this translation in an attempt to show the author of this PR an example of development process. We produced a test build and I have it running fine on my phone. So if you have any issues building this, let me know and I'll look into it.

* I have no idea how the disaster (`+` at the start of each line) in `app/src/main/res/values-pt-rBR/strings.xml` happened, probably someone was trying to produce a pull request by copying a diff from another. We fixed this file here. It's unrelated to the topic of this PR, but will have to be done anyway in order to build the app, and no other PR seems to do this.
* I recall I had to add another Maven repo as suggested by Android Studio, because one of the libraries was missing. This change is **not** included here since if you already have this library locally, you may prefer to use that. Besides, Android Studio made a number of changes to make the project buildable, and not all of them I completely understand, so I didn't feel comfortable sending them. We decided to stick with just the translations.

**Comment by D-side** [comment]
@LukeStonehm sorry to bother, any news on this? Need any help perhaps?

**Comment by LukeStonehm** [comment]
I rewrote the app :see_no_evil: 

I'll port this Russian translation into the new version :)

**Comment by LukeStonehm** [comment]
Done! #70 is no longer required as the changes have been included in #75 
Thank you @Sad-Scientist

**Pull request closed without merging**
