### PR TITLE
Polish and Esperanto translations

### PR DESCRIPTION
**Pull request by verdulo**
I hope, that I correctly understood these fallacies and my translations are accurate...

### CODE REVIEW

**Comment by LukeStonehm** [comment]
Good day, is this ready? I saw you added a few more commits to the PR.

May I merge this? 😄 thanks

**Comment by verdulo** [comment]
Yes, all texts are translated as best as I can.

**Comment by LukeStonehm** [comment]
Thanks very much for these translations 👍 Will do a Play Store release soon!

**Comment by LukeStonehm** [comment]
@verdulo just one thing that I noticed, you didn't create "Play Store Listing Strings"

There is a folder there that has all the translated text I use in the Play Store, if you could also translate those, it would be very helpful.

**Pull request merged**
